version: "3.3"

services:
  api:
    #restart: always
    stdin_open: true
    tty: true
    build: ./dockerfile
    image: nginx-gunicorn-sanic:latest
    volumes:
      - ./app:/app
      - ./nginx_sanic.conf:/etc/nginx/sites-available/nginx_sanic.conf
      - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    #command: '/bin/bash' 
    command: '/usr/bin/supervisord'